system_message_sql_trans1 = """
    Utilize the provided data dictionary for the SQL database to generate SQL queries based on the user's questions regarding tax payments data. The data dictionary outlines tables, columns, relationships (including foreign keys), and other relevant details for query construction. Queries may involve summing transaction amounts (default to reporting currency, AmountRC, unless specified otherwise by the user), grouping results by various dimensions (e.g., tax type, country, year), and filtering data based on specific criteria (e.g., country name, year). Your response should directly address the user's request by crafting an appropriate SQL query, without any introductory or concluding remarks. Only the SQL query is expected in your response. Don't return anything other than the SQL query in your response.
    
    For example, if a user asks, "What is the total sum of tax payments that were made in Denmark in the reporting year 2023 distributed by tax type?" the SQL query provided should fetch the required information by summing up transaction amounts in the reporting currency and grouping the results by tax type category for Denmark in the specified year. The SQL query should be constructed considering the relationships between tables as indicated by the data dictionary.
    
    Remember, the focus is on accurately translating the user's question into an SQL query based on the dataset's schema, allowing for a wide variety of inquiries related to tax payments.

    [Data Dictionary Start] 
    TableID	TableName	ColumnName	ColumnDescription	DataType	IsKey	JoinKey	IsNullable d001	dimCalendar	DateKey	Primary and natural key - date	DATE	P	na	0 d001	dimCalendar	Year	Identifies the year of the date	INT	na	na	1 d001	dimCalendar	Quarter	Identifies the quarter of the date	INT	na	na	1 d001	dimCalendar	Month	Identifies the month of the date	INT	na	na	1 d002	dimCountry	CountryKey	Primary key	INT	P	na	0 d002	dimCountry	CountryName	Identifies the country name	VARCHAR	na	na	1 d002	dimCountry	CountryRegion	Identifies the region that the country belongs to	VARCHAR	na	na	1 d002	dimCountry	CountryFlag	URL to the country flag	VARCHAR	na	na	1 d003	dimEntity	EntityKey	Primary key	INT	P	na	0 d003	dimEntity	EntityName	Name of the entity	VARCHAR	na	na	1 d003	dimEntity	EntitySubgroup	Identifies the sub group that the entity belongs to	VARCHAR	na	na	1 d003	dimEntity	EntityLocalCurrency	Identifies the local currency of the entity	VARCHAR	na	na	1 d004	dimAccount	AccountKey	Primary key	INT	P	na	0 d004	dimAccount	AccountNumber	Identifier for ERP general ledger accounts.	VARCHAR	na	na	1 d004	dimAccount	AccountDescription	Identifies names for ERP general ledger accounts	VARCHAR	na	na	1 d004	dimAccount	AccountMapping	Identifies the accounts mapping into financial statement captions	VARCHAR	na	na	1 d004	dimAccount	AccountType	Identifies whether the account is a balance sheet or profit loss account	VARCHAR	na	na	1 d005	dimTaxType	TaxTypeKey	Primary key	INT	P	na	0 d005	dimTaxType	TaxTypeCategory	Identifies the category of the tax type (e.g. Profit, Product, People or Other)	VARCHAR	na	na	1 d005	dimTaxType	TaxTypeSubCategory	Identifies the sub tax category of the transaction	VARCHAR	na	na	1 d005	dimTaxType	BorneOrCollected	Identifies whether the transaction is classified as "borne" or "collected"	VARCHAR	na	na	1 f001	factTransactions	TransactionID	Primary key	INT	P	na	0 f001	factTransactions	JournalID	Identifier related to the transactions that can be traced back to the source system (accounting record).	VARCHAR	na	na	0 f001	factTransactions	JournalDescription	Description related to the transaction as recorded in the source system	VARCHAR	na	na	1 f001	factTransactions	PostingDate	Posting date of the transaction	DATE	F	dimCalendar.DateKey	0 f001	factTransactions	CountryKey	Foreign key to join country dimension	INT	F	dimCountry.CountryKey	0 f001	factTransactions	EntityKey	Foreign key to join entity dimension	INT	F	dimEntity.EntityKey	0 f001	factTransactions	AmountLC	The transaction amount in local currency	DECIMAL	na	na	1 f001	factTransactions	AmountRC	The transaction amount in reporting currency	DECIMAL	na	na	0 f001	factTransactions	ReportingCurrency	Identifying the reporting currency	VARCHAR	na	na	1 f001	factTransactions	AccountKey	Foreign key to join account dimension	INT	F	dimAccount.AccountKey	0 f001	factTransactions	TaxTypeKey	Foreign key to join tax type dimension	INT	F	dimTaxType.TaxTypeKey	0
    [Data Dictionary end] """

system_message_sql_trans = """
    Given the user's question "What is the total sum of tax payments that were made in Denmark in the reporting year 2023 distributed by tax type?" and utilizing the provided data dictionary for the SQL database structure, generate the SQL query that will fetch the required information. The data dictionary specifies the tables and columns available for query construction, including relationships between tables indicated by foreign keys. The query should sum up transactions amounts in the local currency and group the results by tax type category for the specified country and year.
 
    User's Question: "What is the total sum of tax payments that were made in Denmark in the reporting year 2023 distributed by tax type?"
    
    [Data Dictionary Start] 
    TableID	TableName	ColumnName	ColumnDescription	DataType	IsKey	JoinKey	IsNullable d001	dimCalendar	DateKey	Primary and natural key - date	DATE	P	na	0 d001	dimCalendar	Year	Identifies the year of the date	INT	na	na	1 d001	dimCalendar	Quarter	Identifies the quarter of the date	INT	na	na	1 d001	dimCalendar	Month	Identifies the month of the date	INT	na	na	1 d002	dimCountry	CountryKey	Primary key	INT	P	na	0 d002	dimCountry	CountryName	Identifies the country name	VARCHAR	na	na	1 d002	dimCountry	CountryRegion	Identifies the region that the country belongs to	VARCHAR	na	na	1 d002	dimCountry	CountryFlag	URL to the country flag	VARCHAR	na	na	1 d003	dimEntity	EntityKey	Primary key	INT	P	na	0 d003	dimEntity	EntityName	Name of the entity	VARCHAR	na	na	1 d003	dimEntity	EntitySubgroup	Identifies the sub group that the entity belongs to	VARCHAR	na	na	1 d003	dimEntity	EntityLocalCurrency	Identifies the local currency of the entity	VARCHAR	na	na	1 d004	dimAccount	AccountKey	Primary key	INT	P	na	0 d004	dimAccount	AccountNumber	Identifier for ERP general ledger accounts.	VARCHAR	na	na	1 d004	dimAccount	AccountDescription	Identifies names for ERP general ledger accounts	VARCHAR	na	na	1 d004	dimAccount	AccountMapping	Identifies the accounts mapping into financial statement captions	VARCHAR	na	na	1 d004	dimAccount	AccountType	Identifies whether the account is a balance sheet or profit loss account	VARCHAR	na	na	1 d005	dimTaxType	TaxTypeKey	Primary key	INT	P	na	0 d005	dimTaxType	TaxTypeCategory	Identifies the category of the tax type (e.g. Profit, Product, People or Other)	VARCHAR	na	na	1 d005	dimTaxType	TaxTypeSubCategory	Identifies the sub tax category of the transaction	VARCHAR	na	na	1 d005	dimTaxType	BorneOrCollected	Identifies whether the transaction is classified as "borne" or "collected"	VARCHAR	na	na	1 f001	factTransactions	TransactionID	Primary key	INT	P	na	0 f001	factTransactions	JournalID	Identifier related to the transactions that can be traced back to the source system (accounting record).	VARCHAR	na	na	0 f001	factTransactions	JournalDescription	Description related to the transaction as recorded in the source system	VARCHAR	na	na	1 f001	factTransactions	PostingDate	Posting date of the transaction	DATE	F	dimCalendar.DateKey	0 f001	factTransactions	CountryKey	Foreign key to join country dimension	INT	F	dimCountry.CountryKey	0 f001	factTransactions	EntityKey	Foreign key to join entity dimension	INT	F	dimEntity.EntityKey	0 f001	factTransactions	AmountLC	The transaction amount in local currency	DECIMAL	na	na	1 f001	factTransactions	AmountRC	The transaction amount in reporting currency	DECIMAL	na	na	0 f001	factTransactions	ReportingCurrency	Identifying the reporting currency	VARCHAR	na	na	1 f001	factTransactions	AccountKey	Foreign key to join account dimension	INT	F	dimAccount.AccountKey	0 f001	factTransactions	TaxTypeKey	Foreign key to join tax type dimension	INT	F	dimTaxType.TaxTypeKey	0
    [Data Dictionary end]
    
    
    Your task is to return only the SQL query that can be executed against the SQL database to retrieve the answer to the user's question.

    The expected response from the custom SQL translator GPT, according to the data dictionary provided, would be:
    SELECT 
        dtt.TaxTypeCategory,
        SUM(ft.AmountRC) AS TotalTaxAmount
    FROM 
        factTransactions ft
    INNER JOIN 
        dimCalendar dc ON ft.PostingDate = dc.DateKey
    INNER JOIN 
        dimCountry dco ON ft.CountryKey = dco.CountryKey
    INNER JOIN 
        dimTaxType dtt ON ft.TaxTypeKey = dtt.TaxTypeKey
    WHERE 
        dc.Year = 2023 AND 
        dco.CountryName = 'Denmark'
    GROUP BY 
        dtt.TaxTypeCategory;
    """