// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Boilerplate.Domain
{
    public partial class ColTest
    {
        public Guid RecordId { get; set; }
        public string ColString1 { get; set; }
        public string ColString2 { get; set; }
        public bool? ColBoolean { get; set; }
        public int? ColInt { get; set; }
        public decimal? ColNumeric { get; set; }
    }
}